# Generated by Django 3.1.4 on 2020-12-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='studen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField()),
                ('name', models.CharField(max_length=80)),
                ('career', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=300)),
                ('exp', models.IntegerField()),
                ('lv', models.IntegerField()),
            ],
            options={
                'verbose_name': 'studen',
                'verbose_name_plural': 'students',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='week1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=200)),
                ('week1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.courses')),
            ],
        ),
        migrations.CreateModel(
            name='technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('badge', models.URLField()),
                ('technologi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studen')),
            ],
            options={
                'verbose_name': 'technologie',
                'verbose_name_plural': 'technologies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=400)),
                ('repository', models.URLField()),
                ('projec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studen')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['id'],
            },
        ),
    ]
