# Generated by Django 3.1.4 on 2020-12-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='technologies',
            new_name='technologi',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projec',
            new_name='studen_id',
        ),
        migrations.RenameField(
            model_name='technologi',
            old_name='technologi',
            new_name='studen_id',
        ),
        migrations.RenameField(
            model_name='week1',
            old_name='week1',
            new_name='courses_id',
        ),
    ]
