# Generated by Django 3.1.4 on 2020-12-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20201218_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['id'], 'verbose_name': 'week', 'verbose_name_plural': 'weeks'},
        ),
        migrations.RemoveField(
            model_name='studen',
            name='price',
        ),
        migrations.AlterField(
            model_name='studen',
            name='photo',
            field=models.URLField(max_length=500),
        ),
    ]
