# Generated by Django 3.1.4 on 2020-12-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20201218_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'week',
                'verbose_name_plural': 'weeks',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='courses',
            name='milestone',
        ),
        migrations.AddField(
            model_name='courses',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='ur_local',
            field=models.URLField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='week',
        ),
    ]
