# Generated by Django 3.1.4 on 2020-12-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20201218_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['id'], 'verbose_name': 'name', 'verbose_name_plural': 'names'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='technologi',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
